version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postresqlWithmarten
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marten_db
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marten_api
    ports:
      - "8080:8080"
    depends_on:
      - db
